# Generated by Django 5.2.7 on 2025-12-12 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='da',
            name='date_DA',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
