# Generated by Django 5.2.7 on 2025-12-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_da_date_da'),
    ]

    operations = [
        migrations.AlterField(
            model_name='da',
            name='date_DA',
            field=models.DateField(blank=True, null=True),
        ),
    ]
